name: tsa
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - scikit-optimize
  - black
  - pip
  - pip:
    - statsmodels
    - arch
    - yfinance
